---
- name: Open-iscsi
  become: true
  block:
    - name: Install open-iscsi on Debian
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt:
        state: present
        name: open-iscsi
        force: true

    - name: Install open-iscsi on Redhat
      when: ansible_facts['os_family'] == "RedHat"
      become: true
      ansible.builtin.yum:
        state: present
        name: iscsi-initiator-utils

    - name: Active iscsid service
      ansible.builtin.service:
        state: started
        name: iscsid
        enabled: true
