- name: Install harbor
  block:
    - name: Add the harbor Helm repository
      kubernetes.core.helm_repository:
        name: harbor
        repo_url: "{{ harbor_repo }}"

    - name: Install the harbor Helm chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: harbor/harbor
        chart_version: "{{ chart_version }}"
        release_namespace: "{{ release_namespace }}"
        create_namespace: true
        update_repo_cache: true
        values:
          exposureType: ingress
          externalURL: https://{{ core_hostname }}
          ingress:
            core:
              hostname: "{{ core_hostname }}"
              extraTls:
                - hosts:
                    - "{{ core_hostname }}"
                  secretName: harbor-core-identity-certificate-secret
              annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: "{{ cluster_issuer_name }}"
            notary:
              hostname: "{{ notary_hostname }}"
              extraTls:
                - hosts:
                    - "{{ core_hostname }}"
                  secretName: harbor-noraty-identity-certificate-secret
              annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: "{{ cluster_issuer_name }}"
          adminPassword: "{{ harbor_admin_pwd }}"
          proxy:
            # httpProxy: "{{ proxy_host }}"
            # httpsProxy: "{{ proxy_host }}"
            noProxy: 127.0.0.1,localhost,.local,.internal
            components:
              - core
              - jobservice
              - trivy
