---
- name: Deploy Rancher UI Admin
  block:
    - name: Add the Rancher Helm repository
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: "https://releases.rancher.com/server-charts/stable"

    - name: Install the rancher Helm chart (without proxy config)
      when: not use_proxy
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: rancher-stable/rancher
        chart_version: "{{ chart_version }}"
        release_namespace: "{{ release_namespace }}"
        create_namespace: true
        update_repo_cache: true
        values:
          hostname: "{{ rancher_hostname }}"
          bootstrapPassword: "{{ rancher_bootstrapPassword }}"
          # additionalTrustedCAs: "{{ additionalTrustedCAs }}"

    - name: Install the rancher Helm chart (with proxy config)
      when: use_proxy
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: rancher-stable/rancher
        chart_version: "{{ chart_version }}"
        release_namespace: "{{ release_namespace }}"
        create_namespace: true
        update_repo_cache: true
        values:
          http_proxy: http://{{ proxy_host }}
          https_proxy: http://{{ proxy_host }}
          hostname: "{{ rancher_hostname }}"
          bootstrapPassword: "{{ rancher_bootstrapPassword }}"
          # additionalTrustedCAs: "{{ additionalTrustedCAs }}"
