---
- name: Install apps
  hosts: localhost
  tags: apps
  gather_facts: false
  roles:
    - role: apps/cert_manager
      when: install_cert_manager
    - role: apps/storage
      when: install_longhorn
    - role: apps/keycloak
      when: install_keycloak
    - role: apps/harbor
      when: install_harbor
