# Load Balancer Configuration
loadbalancer_address: "10.63.224.54"
domain_name: "{{ loadbalancer_address }}.sslip.io"

# Proxy Configuration
use_proxy: false
proxy_host: 192.168.42.15:3128

 # User Configuration
user: ubuntu

 # Kubernetes Configuration
apiserver_port: 6443
join_cluster_port: 9345
kube_config_directory: "/home/{{ user }}/.kube"
rke2_data_dir: "/var/lib/rancher/rke2"
cluster_token: fbf77b7e4e40d763ad4df32ec9e02d877b112eab

 # Installations
install_cert_manager: false
install_longhorn: false
install_keycloak: false
install_harbor: false
cluster_issuer_name: selfsigned-cluster-issuer