---
- name: Deploy Longhorn Provider strorage
  block:
    - name: Add the Longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    - name: Deploy the Longhorn Helm chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: longhorn/longhorn
        chart_version: "{{ chart_version }}"
        release_namespace: "{{ release_namespace }}"
        create_namespace: true
        update_repo_cache: true
        # values:
        #   defaultSettings:
        #     createDefaultDiskLabeledNodes: true
        #     defaultDataPath: /data/longhorn
