---
- name: Open-iscsi
  become: true
  block:
    - name: Install open-iscsi on Debian
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt:
        state: present
        name: open-iscsi
        force: true

    - name: Active iscsid service
      ansible.builtin.service:
        state: started
        name: iscsid
        enabled: true
